### PR TITLE
chore: no magic strings

### PR DESCRIPTION
**Pull request by BenjaminPalko**

### CODE REVIEW

**Review by piopi — COMMENTED** [review]
Don't think you should use translation for API errors

**Comment by BenjaminPalko** [comment]
> Don't think you should use translation for API errors

They are form errors, we could return a flag from the server then serve the message on the client. Its an extra step, but does that make sense?

**Comment by piopi** [comment]
> > Don't think you should use translation for API errors
> 
> They are form errors, we could return a flag from the server then serve the message on the client. Its an extra step, but does that make sense?


It makes sense, I like that way!

**Comment by BenjaminPalko** [comment]
> > > Don't think you should use translation for API errors
> > 
> > 
> > They are form errors, we could return a flag from the server then serve the message on the client. Its an extra step, but does that make sense?
> 
> It makes sense, I like that way!

Opened #35 for this work, its a bit more involved than what Im doing here since we need a system for passing errors from the backend to the frontend + form needs to properly handle error states

**Comment by piopi** [comment]
@BenjaminPalko Can you remove please the translation from the api 🙏🏽

**Review by piopi — APPROVED** [review]

**Pull request merged**
